language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install tox-travis

script:
  - tox

deploy:
  provider: pypi
  user: lodge93
  distributions: sdist bdist_wheel
  password:
    secure: ZcQFG96IscAHWJsMw8PNtbBBE7udUoAD4IXArYGeMM1FyNxFG2wYXXIbaxSMrHfQ2wxEXXsUxXRyg7H7moOTBsvs71XzIkTkY6nvjFJxB0E8y/VziINvqbXLtz0UbbWE97KLc9otJTOlfwHgKiCLzOMH5rmsioyZd3wtJaiQ/EDq+uiVcsPR/HtLGlsQmn6m61NZTBQKA1ksHQP4IiuT4gOunSMQzso1JKXuv7Ivgoyi9CJECJsOMpPfWdBqup4jnlMr0ZzLxp0w11LLk4eueY+MYWJ6hDM3wEL7gXPCGVNyvp0yjW1iJUR+3cw5gl5SigxPTpGybd5XxBVda/uP1tmRpUdloxCw1CV+Wssl3bovmaLM+AbHa2eLLoW6K5RRZosrJ94FPC9i+VmlSdm3+WiHp6iAvgiCxWwwtYBCW7TNg8VLgFpKkPlMlbzU4SgIZvkp6OAcmEmFRSF46f004frIS6SAGCypyShYkYbr+J4BhCsrEVW/i8u7wKLz93qVLux4u1eao8g1Cu/WIVI9Bii0fbsFQ9y3L3TgyehS1D3N1Jij8aDHxGugVYnKffnZY7NfiFUjxfZLvEyc47bNCwuwtNoIwSmDjfSds59j0+Eg7rac1L0+HLL5YKt9PH1pv9+N044teReOEFeyJyufu5/Uqby+mk9akuZIapcjECM=
  on:
    tags: true
